---
title: "Variables más importantes"
author: "Tingting"
date: "2024-05-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Variables más importantes

### Priority Lasso

```{r}
#Remove suffixes
remove_suffixes <- function(variable_list) {
  sapply(variable_list, function(x) {
    if (grepl("\\.TF$", x)) {
      return(x)  
    } else {
      return(sub("\\..*", "", x))  
    }
  })
}

important_vars_PLasso <- list(
  differentiated = remove_suffixes(c("MIR3140.CNV", "OGFRL1.CNV", "LINC00472.CNV", "MIR30C2.CNV", "MIR30A.CNV", "RN7SKP106.CNV", 
                                     "MIR4466.CNV", "VPS13B.CNV", "MED30.CNV", "FZD2.CNV", "cg00658007.Methyl", "cg01033938.Methyl", 
                                     "cg02397720.Methyl", "cg03019000.Methyl", "cg03439703.Methyl", "cg03557733.Methyl", "cg04101379.Methyl", 
                                     "cg08504583.Methyl", "cg09243900.Methyl", "cg10523671.Methyl", "cg11765205.Methyl", "cg14896003.Methyl", 
                                     "cg16504798.Methyl", "cg17063929.Methyl", "cg17240454.Methyl", "cg20437604.Methyl", "cg21096399.Methyl", 
                                     "cg23732182.Methyl", "cg23851011.Methyl", "cg27016307.Methyl", "SMAD3.TF", "BRIP1.TF", "RNGTT.TF", 
                                     "PER2.TF", "NKX6.1.TF", "BARX1.TF", "TCF19.TF", "TRIP6.TF", "BCL11B.TF", "ARX.TF")),
  
  immunoreactive = remove_suffixes(c("YTHDF2.CNV", "MARCKSL1.CNV", "TACSTD2.CNV", "VTCN1.CNV", "PRPF3.CNV", "ADI1.CNV", "RNASEH1.CNV", 
                                     "MBOAT2.CNV", "snoU13.ENSG00000238888.1.CNV", "C2orf42.CNV", "TACR1.CNV", "COL4A4.CNV", "CAB39.CNV", 
                                     "LARS2.CNV", "MED12L.CNV", "UGT2A1.CNV", "UGT2A2.CNV", "RUFY3.CNV", "snoU13.ENSG00000238318.1.CNV", 
                                     "GRSF1.CNV", "BTC.CNV", "CXCL13.CNV", "MANBA.CNV", "GRIA2.CNV", "RPA3.CNV", "GLCCI1.CNV", "CHMP5.CNV", 
                                     "NFX1.CNV", "IGFBPL1.CNV", "ARL5B.CNV", "RN7SL571P.CNV", "CHURC1.CNV", "GPX2.CNV", "FNTB.CNV", "MAX.CNV", 
                                     "MIR4706.CNV", "TMC5.CNV", "SAP30BP.CNV", "UNC13D.CNV", "MIR3929.CNV", "SYT4.CNV", "RNF165.CNV", 
                                     "TASP1.CNV", "RN7SL243P.CNV", "USP25.CNV", "snoU13.ENSG00000238591.1.CNV", "XBP1.CNV", "ACO2.CNV", 
                                     "RN7SKP194.CNV", "cg08727202.Methyl", "cg14070162.Methyl", "cg22820108.Methyl", "hsa.miR.142.5p.miRNA", 
                                     "hsa.miR.337.5p.miRNA", "hsa.miR.379.5p.miRNA", "hsa.miR.455.3p.miRNA", "BRD3.TF", "DDIT3.TF", "SLA2.TF", 
                                     "PMEPA1.TF", "TBX21.TF", "GLIS2.TF", "CDK6.TF", "SPI1.TF", "KDM6B.TF", "NCOR2.TF", "SP140.TF", "ABL1.TF", 
                                     "HEYL.TF", "NR1H3.TF", "ETV7.TF", "NFIX.TF")),
  
  mesenchymal = remove_suffixes(c("FGR.CNV", "SRSF4.CNV", "KIAA0319L.CNV", "HYI.CNV", "CYP4Z1.CNV", "C8A.CNV", "PHTF1.CNV", "AP4B1.CNV", 
                                  "DCLRE1B.CNV", "OLFML3.CNV", "MRPL9.CNV", "OAZ3.CNV", "TDRKH.CNV", "LINGO4.CNV", "RORC.CNV", "KIAA0907.CNV", 
                                  "XPR1.CNV", "RNA5SP73.CNV", "LINC00303.CNV", "KLHDC8A.CNV", "CENPF.CNV", "THADA.CNV", "CLHC1.CNV", "RPS27A.CNV", 
                                  "MTIF2.CNV", "METAP1D.CNV", "ITGA6.CNV", "HOXD9.CNV", "HOXD8.CNV", "HOXD4.CNV", "MIR10B.CNV", "PTPRG.CNV", 
                                  "IMPG2.CNV", "SENP7.CNV", "DZIP3.CNV", "ATP6V1A.CNV", "BCHE.CNV", "SNORA18.ENSG00000200288.1.CNV", "NIPAL1.CNV", 
                                  "CNGA1.CNV", "SNORD42.ENSG00000202440.1.CNV", "HNRNPDL.CNV", "LINC00290.CNV", "DNAH5.CNV", "PARP8.CNV", 
                                  "MOCS2.CNV", "RN7SL801P.CNV", "MIR4459.CNV", "CKS1B.ENSG00000268942.1.CNV", "LRRC70.CNV", "ZBED3.CNV", 
                                  "NBPF22P.CNV", "RN7SKP62.CNV", "DUSP22.CNV", "EXOC2.CNV", "HUS1B.CNV", "IRF4.CNV", "HECW1.CNV", "ATXN7L1.CNV", 
                                  "MIR4469.CNV", "FNTA.CNV", "TSPYL5.CNV", "U3.ENSG00000207215.1.CNV", "SMARCA2.CNV", "DMRTA1.CNV", "FAM205CP.CNV", 
                                  "SPTLC1.CNV", "C9orf3.CNV", "MIR4668.CNV", "PBX3.CNV", "RTKN2.CNV", "PANK1.CNV", "SNORD112.ENSG00000253068.1.CNV", 
                                  "DRD4.CNV", "BBOX1.CNV", "RN7SKP158.CNV", "FOLH1.CNV", "SDHAF2.CNV", "RN7SL23P.CNV", "CD248.CNV", "RIN1.CNV", 
                                  "BRMS1.CNV", "B3GNT1.CNV", "ZBTB44.CNV", "ABCD2.CNV", "C12orf40.CNV", "PRICKLE1.CNV", "ERBB3.CNV", "PA2G4.CNV", 
                                  "RPL41.CNV", "ZC3H10.CNV", "RN7SL770P.CNV", "SDR9C7.CNV", "TRPC4.CNV", "LPAR6.CNV", "OR5AU1.CNV", "PSMA6.CNV", 
                                  "LINC00642.CNV", "RN7SL710P.CNV", "IREB2.CNV", "SOX8.CNV", "GLIS2.CNV", "PAM16.CNV", "VASN.CNV", "RNA5SP403.CNV", 
                                  "CACNG3.CNV", "SNORA1.ENSG00000201541.1.CNV", "FUS.CNV", "C16orf98.CNV", "PYCARD.CNV", "TK2.CNV", "CKLF.CNV", 
                                  "CMTM1.CNV", "CMTM2.CNV", "CMTM3.CNV", "MIR744.CNV", "NT5M.CNV", "MED9.CNV", "KRT33A.CNV", "KRT33B.CNV", "KRT31.CNV", 
                                  "KRT34.CNV", "KRT37.CNV", "C17orf104.CNV", "CCDC43.CNV", "RN7SL819P.CNV", "PSMD12.CNV", "ROCK1P1.CNV", "THOC1.CNV", 
                                  "USP14.CNV", "MIR122.CNV", "ZNF77.CNV", "TLE6.CNV", "UHRF1.CNV", "MIR4999.CNV", "RAB11B.CNV", "NR2F6.CNV", "USHBP1.CNV", 
                                  "NXNL1.CNV", "LPAR2.CNV", "TSHZ3.CNV", "THEG5.CNV", "KIAA0355.CNV", "CABP5.CNV", "DEFB116.CNV", "COMMD7.CNV", 
                                  "RN7SL636P.CNV", "JAM2.CNV", "ATP5J.CNV", "GABPA.CNV", "MYH9.CNV", "AMOT.CNV", "MIR4329.CNV", "RN7SL266P.CNV", 
                                  "snoU13.ENSG00000238811.1.CNV", "XPNPEP2.CNV", "SASH3.CNV")),
  
  proliferative = remove_suffixes(c("SNHG3.CNV", "SNORA73B.CNV", "snoU13.ENSG00000238821.1.CNV", "MECR.CNV", "CELSR2.CNV", "MIR557.CNV", 
                                    "XCL2.CNV", "PLXNA2.CNV", "ACP1.CNV", "FAM110C.CNV", "THSD7B.CNV", "PLEKHA3.CNV", "UBE2E3.CNV", 
                                    "MIR3133.CNV", "NSUN3.CNV", "EPHA6.CNV", "SLC9C1.CNV", "SLC35A5.CNV", "ZBBX.CNV", "BOD1L1.CNV", 
                                    "MIR5091.CNV", "RN7SL492P.CNV", "RN7SL357P.CNV", "SPINK2.CNV", "RNA5SP163.CNV", "BTC.CNV", "MANBA.CNV", 
                                    "SEMA5A.CNV", "snoU13.ENSG00000238702.1.CNV", "ISL1.CNV", "ADAM19.CNV", "RUFY1.CNV", "HDGFL1.CNV", 
                                    "B3GAT2.CNV", "CD109.CNV", "SNORA33.ENSG00000202283.1.CNV", "SNORD46.ENSG00000201009.1.CNV", 
                                    "U6.ENSG00000272393.1.CNV", "MIR5692A2.CNV", "DLC1.CNV", "CCDC25.CNV", "MIR4469.CNV", "STMN2.CNV", 
                                    "MMP16.CNV", "RNA5SP272.CNV", "VPS13B.CNV", "GRHL2.CNV", "ATP6V1C1.CNV", "BAALC.CNV", "COL14A1.CNV", 
                                    "CHMP5.CNV", "NFX1.CNV", "AQP7.CNV", "ABL1.CNV", "SNORD2.ENSG00000238707.1.CNV", "TACC2.CNV", 
                                    "OR4X2.CNV", "TRIM49B.CNV", "TRIM64C.CNV", "GLYATL2.CNV", "GLYATL1P2.CNV", "SLC22A11.CNV", "LRP6.CNV", 
                                    "SLC15A5.CNV", "snoU13.ENSG00000239033.1.CNV", "ALG10B.CNV", "ALG10.CNV", "RNA5SP358.CNV", "RNA5SP359.CNV", 
                                    "SYT10.CNV", "LRRK2.CNV", "ADAMTS20.CNV", "TMEM19.CNV", "PTPN11.CNV", "RPL6.CNV", "IQCD.CNV", "DCLK1.CNV", 
                                    "LPAR6.CNV", "LINC00641.CNV", "GMFB.CNV", "SLC35F4.CNV", "SIX6.CNV", "FUT8.CNV", "RCOR1.CNV", "CHP1.CNV", 
                                    "WDR72.CNV", "CLCN7.CNV", "PTX4.CNV", "TELO2.CNV", "NOXO1.CNV", "GFER.CNV", "SYNGR3.CNV", "CPD.CNV", 
                                    "RAPGEFL1.CNV", "ARSG.CNV", "SRP68.CNV", "EXOC7.CNV", "GALR2.CNV", "LRRC30.CNV", "PTPRM.CNV", 
                                    "SLC14A1.CNV", "CDH20.CNV", "FSTL3.CNV", "PRSS57.CNV", "PALM.CNV", "S1PR4.CNV", "NCLN.CNV", "CASP14.CNV", 
                                    "SLC35E1.CNV", "TMEM38A.CNV", "DYRK1B.CNV", "FBL.CNV", "MIR641.CNV", "KLK15.CNV", "KLK2.CNV", "KLK3.CNV", 
                                    "KLK4.CNV", "KLKP1.CNV", "MGME1.CNV", "RALY.CNV", "TP53INP2.CNV", "MIR648.CNV", "AP1B1.CNV", "TXN2.CNV", 
                                    "UPK3A.CNV", "LINC00899.CNV", "C22orf26.CNV", "CDPF1.CNV", "PKDREJ.CNV", "TTC38.CNV", "SLC9A7.CNV", 
                                    "PHF16.CNV", "PAGE4.CNV", "USP27X.CNV", "SRPX2.CNV", "TSC22D3.CNV", "FGF13.CNV"))
)

```

### Priority lasso 1vs1

```{r}

important_vars_differentiated_b <- c(
  "FGGY.CNV", "MIR4711.CNV", "HOOK1.CNV", "LINC00578.CNV", "SNORA18.ENSG00000200288.1.CNV", 
  "PLXNA4.CNV", "KIAA1429.CNV", "DPY19L4.CNV", "RGS22.CNV", "SNORD77.ENSG00000212414.1.CNV", 
  "MIR1273A.CNV", "FBXO43.CNV", "NCALD.CNV", "DEPTOR.CNV", "RNA5SP277.CNV", 
  "SNTB1.CNV", "ZFAND5.CNV", "TMC1.CNV", "snoU13.ENSG00000238402.1.CNV", "TYR.CNV", 
  "NOX4.CNV", "cg00083937.Methyl", "cg00208967.Methyl", "cg00407150.Methyl", 
  "cg00433406.Methyl", "cg00511475.Methyl", "cg00622552.Methyl", "cg00891541.Methyl", 
  "cg00925717.Methyl", "cg01033938.Methyl"
)

important_vars_proliferative_b <- c(
  "LACTBL1.CNV", "RN7SKP62.CNV", "RIMS1.CNV", "ZMAT4.CNV", "ADAMTS20.CNV", 
  "ANO6.CNV", "ITCH.CNV", "VSTM2L.CNV", "RN7SKP185.CNV", "HSPA13.CNV", 
  "USP25.CNV", "snoU13.ENSG00000238591.1.CNV", "cg00105253.Methyl", "cg00126657.Methyl", 
  "cg00128877.Methyl", "cg00135056.Methyl", "cg00280894.Methyl", "cg00311768.Methyl", 
  "cg00392257.Methyl", "cg00488364.Methyl", "cg00633969.Methyl", "cg00800095.Methyl", 
  "cg00859655.Methyl", "cg00947019.Methyl", "cg01040850.Methyl", "cg01053621.Methyl", 
  "cg01055695.Methyl", "cg01120308.Methyl"
)


important_vars_differentiated_clean_b <- remove_suffixes(important_vars_differentiated_b)
important_vars_proliferative_clean_b <- remove_suffixes(important_vars_proliferative_b)


important_vars_Plasso_binario <- list(
  differentiated = important_vars_differentiated_clean_b,
  proliferative = important_vars_proliferative_clean_b
)


```

### Random Forest

```{r}
important_vars_RF <- list(
  differentiated = c("cg01033938", "cg00662556", "cg19514469", "hsa.miR.214.3p", "cg10368842", "cg18053607", "RNA5SP71", 
                     "PRKAG3", "DDIT4L", "RPS3A", "SNORD73", "RNA5SP169", "KCNIP1", "RN7SL415P", "RNU6ATAC41P", "RN7SKP171", 
                     "TLR4", "C10orf91", "EIF4G2", "MIR326", "KRT83", "GPR135", "LONP2", "PELP1", "SLC16A11", "SPAG5", 
                     "SDF2", "TBC1D3", "BFSP1", "DUSP15", "GSC2", "CHDC2", "PAK3", "cg01252496", "cg03464416", "cg03743584", 
                     "cg04155026", "cg04301375", "cg05428978", "cg05982504", "cg07387199", "cg07823492", "cg07832674", 
                     "cg08675585", "cg09837648", "cg10236239", "cg11719297", "cg11822932", "cg12457773", "cg13877465", 
                     "cg14709524", "cg15059932", "cg15253243", "cg15298594", "cg17582777", "cg17983064", "cg19502744", 
                     "cg19682367", "cg19998328", "cg23352695", "cg23851011", "cg25685838", "cg26991946", "hsa.miR.103a.3p", 
                     "hsa.miR.184", "RBM14.1", "SKP2.1", "KDM6B.1", "AURKAIP1", "ADC", "DNALI1", "RN7SL62P", "GLIS1", 
                     "SLC44A5", "FCRL1", "SNORD112.ENSG00000252946.1", "AGBL5", "R3HDM1", "SPOPL", "SP9", "BOK", "SRGAP3", 
                     "ROBO2", "LINC00636", "RN7SL582P", "CHRD", "LRPAP1", "FAM86EP", "NUDT9", "EGF", "MIR3139", "PET112", 
                     "RN7SL37P", "SERINC5", "SOWAHA", "SAP30L", "SLC26A8", "IBTK", "CCDC162P", "RN7SKP51", "ASF1A", 
                     "ARHGAP18", "IFNGR1", "PBOV1", "RNA5SP220", "PEX3", "PNLDC1", "KMT2C", "TMEM66", "PPP2CB", "DDHD2", 
                     "C8orf86", "C8orf34", "UQCRB", "RGS22", "PABPC1", "UBR5", "AZIN1", "RSPO2", "PYCRL", "ZNF623", 
                     "SLC52A2", "NFX1", "GDF10", "TET1", "C10orf105", "OR51I2", "AKIP1", "snoU13.ENSG00000238387.1", 
                     "E2F8", "OR8H3", "SLC43A3", "FADS3", "RIN1", "KLRAP1", "GYS2", "RNA5SP354", "MANSC4", "TSPAN11", 
                     "PRICKLE1", "NPFF", "SACS", "VWA8", "TMCO3", "OR11H12", "OR10G3", "OXA1L", "EXOC3L4", "U8.ENSG00000238519.1", 
                     "SPG11", "DIS3L", "SOX8", "DNAH3", "RN7SL774P", "ZFP3", "SNORA69.ENSG00000212206.1", "MYH10", "GAS7", 
                     "CDRT7", "NT5M", "MYL4", "EPX", "TRIM47", "SNORA73.ENSG00000199977.1", "TPRX1", "CACNG7", "DEFB116", 
                     "SNORA71.ENSG00000201811.1", "SNORD12B", "MIR548X", "P2RX6P", "PATZ1", "ARMCX3", "OCRL", "FAM127A", 
                     "cg00728317", "cg00799727", "cg00862041", "cg00932276", "cg01119135", "cg01200177", "cg01390445", 
                     "cg01643624", "cg01747665", "cg02507952", "cg02641095", "cg03048535", "cg03866607", "cg03962522", 
                     "cg03964111", "cg04060275", "cg04223956", "cg04365980", "cg04471507", "cg04499325", "cg04518808", 
                     "cg04914105", "cg05286874", "cg05547500", "cg05654164"),
  immunoreactive = c("cg15783800", "ZNF697.1", "HIC1.1", "cg01200177", "cg25417405", "hsa.miR.214.3p", "cg14506552", 
                     "cg18053607", "cg08859675", "RUNX1T1.1", "ETV7.1", "cg20664247", "ETV1.1", "ZMIZ1.1", "cg00546897", 
                     "cg00059225", "cg15379633", "PRDM6.1", "hsa.miR.382.5p", "cg02675652", "cg19514469", "TIE1", "COG2", 
                     "ANAPC1", "WNT6", "RPS3A", "CSF2", "TBC1D22B", "U6.ENSG00000272393.1", "NACAP1", "RN7SL348P", 
                     "HMOX2", "CYB5D2", "ARHGAP28", "cg02500392", "cg04396791", "cg04523589", "cg05335315", "cg06183267", 
                     "cg06192753", "cg07015079", "cg07152925", "cg08495878", "cg09676390", "cg12867448", "cg13628514", 
                     "cg16989646", "cg18997129", "cg19154173", "cg20011833", "cg20179697", "cg20716119", "cg21435394", 
                     "cg21547708", "cg21740204", "cg22678136", "cg24596472", "cg24621042", "cg26521404", "cg26991946", 
                     "hsa.miR.222.3p", "hsa.miR.616.3p", "SAFB.1", "IRF1.1", "RFX2.1", "TAL1.1", "CBX1.1", "TSSK3", 
                     "EPS15", "GLIS1", "NEGR1", "PTBP2", "TARS2", "POGZ", "CD48", "KISS1", "SNORD112.ENSG00000252853.1", 
                     "SNORA2.ENSG00000206647.1", "MYCN", "KCNK3", "SLC30A6", "TLX2", "FUNDC2P2", "RN7SL548P", "LIMS3.ENSG00000257207.4", 
                     "R3HDM1", "TANC1", "DHRS9", "C2orf66", "SLC4A3", "SRGAP3", "QRICH1", "RN7SL504P", "U8.ENSG00000253004.1", 
                     "TMEM150C", "ATOH1", "BMPR1B", "RNA5SP169", "RN7SKP67", "ETF1", "LARS", "RN7SL791P", "RN7SL868P", 
                     "SLC36A2", "MIR3141", "RN7SL295P", "SNX3", "MIR1202", "FOXK1", "ASL", "MIR182", "RN7SKP32", "C8orf34", 
                     "C8orf87", "KLF10", "PTP4A3", "ZNF623", "SNORD27.ENSG00000251699.1", "CHMP5", "CDK20", "GNG10", 
                     "FCN1", "TRAF2", "NUTM2A", "DNMBP", "CYP17A1", "TCF7L2", "HABP2", "MIR3944", "OVCH2", "DAK", "DIXDC1", 
                     "TECTA", "snoU13.ENSG00000238855.1", "KIAA1467", "FAIM2", "AQP6", "SPRYD3", "NPFF", "TARBP2", 
                     "NPFF", "GTSF1", "WASF3", "KATNAL1", "TNFSF11", "LINC00565", "GCNT3", "SNORA77.ENSG00000221376.1", 
                     "ULK3", "BNC1", "HBA2", "NETO2", "RN7SKP142", "RNF114", "EFNB3", "MIR1288", "COPRS", "LINC00671", 
                     "ICAM1", "CIB3", "AP1M1", "LYPD4", "CD37", "RNF114", "SEC14L3", "CHDC2", "NCBP2L", "cg00076645", 
                     "cg00229387", "cg00537910", "cg00626466", "cg00854637", "cg01252496", "cg01369413", "cg01369850", 
                     "cg01447817", "cg01497576", "cg01525376", "cg01580568", "cg01643624", "cg01745448", "cg01853981", 
                     "cg01946401", "cg01965939", "cg01993576", "cg02089348", "cg02148711", "cg02248486", "cg02254649", 
                     "cg02580606", "cg02717866", "cg02804166", "cg03048535"),
  mesenchymal = c("HIC1.1", "ZNF697.1", "cg19514469", "RUNX1T1.1", "RUNX1.1", "BHLHE22.1", "hsa.miR.199b.5p", "cg00546897", 
                  "GLIS2.1", "cg06491116", "PRDM6.1", "cg00534274", "hsa.miR.214.3p", "cg02675652", "hsa.miR.382.5p", 
                  "cg25417405", "cg20664247", "cg15783800", "cg20050113", "ETV1.1", "PMEPA1.1", "SHOX2.1", "ZEB2.1", 
                  "cg01946401", "cg05906362", "IFFO2", "SLC25A3P1", "LINC00299", "KCNF1", "TLX2", "PLGLB1", "BOK", "SSUH2", 
                  "TACC3", "FAM86EP", "ASB5", "KLF10", "TRAPPC9", "MIR4694", "MIR4694", "cg20050113", "PTPRB", "THAP2", 
                  "SDSL", "LINC00944", "VWA8", "RN7SL774P", "DHX35", "RN7SKP184", "ICOSLG", "cg00891278", "cg01747665", 
                  "cg02252918", "cg02602411", "cg02735071", "cg04396791", "cg04499325", "cg04947157", "cg05067286", 
                  "cg05820087", "cg05949660", "cg06307169", "cg12732155", "cg13463367", "cg13628514", "cg14753432", 
                  "cg15247031", "cg16989646", "cg17252960", "cg17974185", "cg18879041", "cg18919097", "cg19580810", 
                  "cg19632760", "cg20119015", "cg20550118", "cg20587968", "cg20804101", "cg21115977", "cg21529807", 
                  "cg22101098", "cg22594309", "cg23877385", "cg24010336", "cg24206694", "cg24421410", "cg25549459", 
                  "cg25612145", "cg26029902", "cg26799474", "cg27298262", "hsa.miR.127.3p", "hsa.miR.181c.5p", "hsa.miR.299.3p", 
                  "hsa.miR.331.3p", "hsa.miR.409.5p", "hsa.miR.9.5p", "C1orf170", "HNRNPCL1", "KPNA6", "GJB3", "DNALI1", 
                  "ANGPTL3", "NBPF12", "SHC1", "FLAD1", "DCST1", "MYBPH", "WDR54", "FAHD2A", "MARCH7", "SP9", "PLEKHA3", 
                  "DNER", "OR5K3", "ATP13A4", "EGF", "RPS3A", "SLC36A2", "JARID2", "SMAP1", "SNX3", "CDK19", "PLN", 
                  "PNLDC1", "LRRC72", "ASL", "MIR592", "AKR1B1", "MAK16", "RN7SKP32", "GGH", "PYCRL", "ZNF623", "ZNF7", 
                  "CDNF", "C2CD3", "TRPC6", "DIXDC1", "FBXL14", "LRP6", "RNY4P29", "INO80", "RN7SL577P", "AKTIP", "CMTM4", 
                  "GAN", "SPAG5", "EVI2B", "KRT33A", "MIR5010", "OR7G1", "SSBP4", "VRK3", "ZNF211", "TBC1D10A", "MIR378I", 
                  "C22orf26", "cg00229387", "cg00563926", "cg00626466", "cg00796728", "cg00840516", "cg00932276", 
                  "cg00962459", "cg01017147", "cg01036012", "cg01419479", "cg01599709", "cg01745448", "cg01965939", 
                  "cg02105856", "cg02269221", "cg03732545", "cg03962522", "cg04001333", "cg04220579", "cg04544498", 
                  "cg05131835", "cg05208878", "cg05308484", "cg05624196", "cg05668853", "cg05927017", "cg06059810", 
                  "cg06207804", "cg06661994", "cg06974755", "cg07015079", "cg07360692", "cg07816439"),
  proliferative = c("cg16989646", "cg05208878", "cg24250393", "cg00059225", "cg20664247", "cg15154229", "hsa.miR.214.3p", 
                    "cg20050113", "KDM1A.1", "cg02675652", "RN7SKP153", "cg14506552", "MEF2C.1", "cg15379633", "cg19514469", 
                    "cg07233761", "PABPC1", "cg25417405", "cg01033938", "cg03386869", "cg22156632", "cg06899976", 
                    "RUNX1T1.1", "CDK8.1", "GPX7", "NBPF12", "LCE1B", "KISS1", "SNORD112.ENSG00000252946.1", "SEPT10", 
                    "U8.ENSG00000253004.1", "RNF13", "RNA5SP220", "ULBP3", "GRM3", "PILRB", "RN7SL396P", "RN7SL395P", 
                    "MIR876", "MIR4673", "HMX3", "UBQLN3", "FAIM2", "RBMS2", "SNORA38.ENSG00000201042.1", "C14orf182", 
                    "DNAH3", "PELP1", "EVI2B", "YPEL2", "TBC1D3P2", "CIB3", "AP1M1", "ZNF256", "TAB3", "cg00891278", 
                    "cg02217159", "cg02717866", "cg03866607", "cg04527363", "cg04527918", "cg04544498", "cg05067286", 
                    "cg05906362", "cg05982504", "cg06207804", "cg06800962", "cg07015079", "cg07360692", "cg08284151", 
                    "cg11086066", "cg11158729", "cg11290225", "cg11511443", "cg11647681", "cg12062492", "cg12808992", 
                    "cg12949975", "cg14035045", "cg15784615", "cg15913671", "cg17558126", "cg18031008", "cg18182399", 
                    "cg19881177", "cg20442697", "cg20451680", "cg20716119", "cg21572897", "cg22418909", "cg24713204", 
                    "cg24834740", "cg26594445", "cg26656135", "hsa.miR.148a.5p", "hsa.miR.29c.3p", "ZNF8.1", "CDK12.1", 
                    "JARID2.1", "IRF9.1", "FOXF2.1", "SMARCA1.1", "HNRNPL.1", "DIDO1.1", "TFCP2.1", "MIR1256", "S100PBP", 
                    "ADC", "SLC2A1", "BRDT", "KRTCAP2", "NTRK1", "RNA5SP71", "GOLT1A", "SNORD112.ENSG00000252853.1", 
                    "COG2", "RNA5SP79", "FAM150B", "MIR3681", "ASXL2", "Vault.ENSG00000251900.1", "GFPT1", "MIR5000", 
                    "TGOLN2", "LIMS1", "WDR33", "R3HDM1", "snoU13.ENSG00000238481.1", "DHRS9", "U3.ENSG00000252981.1", 
                    "MARS2", "RN7SKP260", "TWIST2", "NPRL2", "ITIH1", "PDHB", "KCNAB1", "MIR570", "RN7SKP96", "UNC5C", 
                    "TRIM2", "FAM198B", "TERT", "ARL15", "LINC00491", "LECT2", "PCDHGB4", "TMED9", "FBXO9", "RN7SKP211", 
                    "CTGF", "PPP1R17", "ADAM22", "RN7SKP198", "EPHA1", "BIN3", "TMEM66", "IKBKB", "MIR599", "RGS22", 
                    "RNU6ATAC8P", "KLF10", "NUDCD1", "C8orf76", "TRIB1", "ZNF623", "SNORD27.ENSG00000251699.1", 
                    "LMX1B", "C9orf50", "TRAF2", "ADIRF", "GRK5", "AKIP1", "ASCL3", "MIR4694", "C2CD3", "ANKRD42", 
                    "TECTA", "ETV6", "DERA", "MANSC4", "TSPAN11", "ALG10", "PRICKLE1", "ADAMTS20", "TMEM117", 
                    "snoU13.ENSG00000238395.1", "DNAJC22", "GTSF1", "MYRFL", "ATP2B1", "RMST", "RAD9B", "P2RX7", 
                    "SPATA13", "TMEM255B", "snoU13.ENSG00000238502.1", "BOLA2B"))

```

### BlockForest

-   General

```{r}
important_vars_BF <- c("SLC45A1", "SLC25A33", "RERE", "SNORA77.ENSG00000221083.1", "SCARNA16.ENSG00000252404.1", 
                  "ERRFI1", "SLC2A7", "PARK7", "LINC00337", "MIR34A", "ESPN", "DFFB", "KCNAB2", "RNA5SP40", "CA6", 
                  "SLC2A5", "TNFRSF9", "PER3", "ATAD3B", "TMEM201", "FAM213B", "RN7SL451P", "ATAD3A", "WRAP73", 
                  "VAMP3", "UTS2", "PRDM16", "PANK4", "UBE2J2", "ARHGEF16", "H6PD", "MIR4252", "SMIM1", "THAP3", 
                  "FAM41C", "CEP104", "C1orf233", "TP73", "GLTPD1", "HES3", "SCNN1D", "GNB1", "ATAD3C", "OR4F16", 
                  "LINC00115", "ENO1", "C1orf86", "NOL9", "CPSF3L", "OR4F5", "FAM87B", "TMEM88B", "DDX11L1", "MEGF6", 
                  "snoU13.ENSG00000239166.1", "RN7SL729P", "PUSL1", "MIR4689", "SPSB1", "ACOT7", "DVL1", "LINC00982", 
                  "C1orf200", "CCDC27", "RPL22", "MTOR", "RN7SL731P", "C1orf64", "PRKCZ", "C1orf174", "PEX14", "PHF13", 
                  "DNAJC11", "ZBTB48", "RER1", "SLC35E2B", "PRAMEF6", "KAZN", "SNORA59A", "RNF207", "CLSTN1", "CDK11B", 
                  "MIR4417", "PEX10", "C1orf159", "PADI2", "SLC35E2", "HES2", "TMEM240", "SAMD11", "TAS1R1", "RN7SL574P", 
                  "IGSF21", "KLHL17", "MMP23B", "TPRG1L", "C1orf222", "PLEKHG5", "PIK3CD", "NOC2L", "CASZ1", "TNFRSF14", 
                  "SSU72", "SPEN", "MORN1", "NBPF1", "RNF223", "ACAP3", "SZRD1", "DDI2", "CLCN6", "GPR157", "MIIP", 
                  "PLCH2", "TNFRSF25", "ISG15", "CCNL2", "EPHA2", "AJAP1", "HSPB7", "CAMTA1", "FAM132A", "RBP7", 
                  "B3GALT6", "RSG1", "MRPL20", "C1orf170", "MIR200B", "MFAP2", "ICMT", "FBXO2", "MIR551A", "PRAMEF14", 
                  "CHD5", "AGMAT", "FHAD1", "TNFRSF4", "C1orf167", "CROCCP2", "PRAMEF4", "VPS13D", "GABRD", "MIR429", 
                  "RN7SL657P", "CROCCP3", "AURKAIP1", "PGD", "AADACL3", "TAS1R3", "TNFRSF18", "TTLL10", "KLHDC7A", 
                  "MXRA8", "KLHL21", "TTC34", "PRAMEF22", "PRAMEF13", "CASP9", "MIR3972", "ANKRD65", "ACTRT2", "SPATA21", 
                  "PTCHD2", "ARHGEF10L", "ANGPTL7", "TMEM52", "MIB2", "AGTRAP", "SDHB", "CROCC", "MMEL1", "TNFRSF1B", 
                  "CTNNBIP1", "MTHFR", "HES5", "FBLIM1", "DFFA", "UBIAD1", "NPHP4", "ANO7P1", "MASP2", "EFHD2", "CALML6", 
                  "GPR153", "PADI6", "UBE4B", "LRRC47", "RSC1A1", "VWA1", "NADK", "AGRN", "U1.ENSG00000228549.2", 
                  "PRAMEF8", "CLCNKA", "MFN2", "LZIC", "RN7SL614P", "snoU13.ENSG00000238818.1", "snoU13.ENSG00000238771.1", 
                  "PRAMEF5", "MST1L", "FAM138A", "PRAMEF16", "PRAMEF19", "KIF1B", "CDK11A", "PRAMEF15", "TARDBP", "ACTL8", 
                  "PRAMEF20", "PRAMEF21", "PADI3", "MIR4632", "MIR5697", "U1.ENSG00000233421.3", "RNA5SP41", "KIAA2013", 
                  "OR4F29", "C1orf195", "PDPN", "PRAMEF17", "PLEKHN1", "PRAMEF2", "SLC25A34", "SCARNA21.ENSG00000251866.1", 
                  "MIR200A", "SKI", "TMEM82", "HES4", "TNFRSF8", "PRAMEF10", "PRAMEF18", "RNU6ATAC18P", "PRAMEF1", "PADI1", 
                  "PLEKHM2", "PADI4", "SDF4", "MIR3675", "C1orf134", "snoU13.ENSG00000239020.1", "APITD1", "MIR1273D", 
                  "PRAMEF11", "PRDM2", "SCARNA11.ENSG00000253085.1", "C1orf158", "NPPB", "SNORA70.ENSG00000252969.1", 
                  "FBXO6", "AADACL4", "MAD2L2", "NPPA", "DHRS3", "IFFO2", "NBL1")

```

-   Binario

```{r}
important_vars_bf_binario <- c(
  "LDLRAD2", "PINK1", "HNRNPR", "PAFAH2", "AKR7L", "MIR4684", "TMCO4", 
  "SCARNA18", "ALPL", "EMC1", "PITHD1", "SRSF10", "PAQR7", 
  "CNR2", "MIR378F", "RN7SL386P", "RCAN3", "HSPG2", "C1QB", "TCEB3", "DDOST", 
  "snoU13", "NBPF3", "SEPN1", "MINOS1", "FAM43B", "ZBTB40", 
  "C1QC", "PLA2G2A", "RN7SL532P", "CDA", "SYF2", "CEP85", "E2F2", "AKR7A2", 
  "RN7SL186P", "ZNF436", "MRTO4", "ID3", "MIR1256", "CELA3B", "RN7SL490P", 
  "CD52", "SH2D5", "PAX7", "snoU13", "CATSPER4", "ASAP3", 
  "AKR7A3", "CDC42", "EXTL1", "SH3BGRL3", "MIR4695", "AIM1L", "EIF4G3", 
  "MIR1290", "NBL1", "MIR3917", "LYPLA2", "AUNIP", "USP48", "RN7SL85P", 
  "TMEM57", "TCEA3", "MTFR1L", "STPG1", "PLA2G5", "SCARNA17", 
  "VWA5B1", "RN7SL277P", "GALE", "MAN1C1", "IFFO2", "MDS2", "RPL11", "CLIC4", 
  "ALDH4A1", "MUL1", "CAMK2N1", "snoU13", "TMEM50A", "UBR4", 
  "SLC30A2", "MIR4419A", "RUNX3", "HP1BP3", "EPHA8", "PLA2G2F", "C1orf63", 
  "EPHB2", "CNKSR1", "MIR4418", "MIR3115", "snoU13", "RHCE", 
  "STMN1", "RAP1GAP", "IL22RA1", "RN7SL857P", "RN7SL24P", "HMGCL", "WNT4", 
  "MYOM3", "RNF186", "MIR4425", "LACTBL1", "PNRC2", "RHD", "HTR1D", "NCMAP", 
  "CAPZB", "FUCA1", "IFNLR1", "RN7SL421P", "UBXN11", "PQLC2", "LUZP1", "ECE1", 
  "LINC00339", "PLA2G2E"
)

```

### PLSDA

```{r}

 important_vars_plsda <- list(
  immunoreactive = variables_immunoreactive,
  proliferative = variables_proliferative,
  mesenchymal = variables_mesenchymal,
  differentiated = variables_differentitated
)

important_vars_plsda_binario <- list(
  proliferative = variables_proliferativebi,
  differentiated = variables_differentiatedbi
)

```

### ELASTICNET-LASSO

```{r}

variables_contributions <- list(
  c('cg08942875', 0.0, 0.0, 100.0, 0.0),
  c('cg13240639', 0.0, 77.5221265104251, 0.0, 0.0),
  c('cg24206694', 49.6109491229466, 0.0, 0.0, 0.0),
  c('cg04402875', 43.8303457475951, 0.0, 0.0, 0.0),
  c('cg00231920', 32.4445083748074, 0.0, 0.0, 0.0),
  c('cg12413566', 0.0, 0.0, 31.5882712061984, 0.0),
  c('cg26891849', 26.2280010052286, 0.0, 0.0, 0.0),
  c('cg11086066', 0.0, 0.0, 21.284714151715, 0.0),
  c('cg24010952', 0.0, 20.0114404677614, 0.0, 0.0),
  c('cg05125838', 0.0, 0.0, 0.0, 19.2210826165024),
  c('cg15783800', 0.0, 0.0, 18.6659048627118, 0.0),
  c('cg09017174', 0.0, 0.0, 17.1351136599603, 0.0),
  c('cg03557733', 15.377746625721, 0.0, 0.0, 0.0),
  c('cg15128898', 0.0, 0.0, 14.4800215035117, 0.0),
  c('cg26680127', 0.0, 0.0, 0.0, 13.3207161649204),
  c('cg13468685', 0.0, 13.172463479986, 0.0, 0.0),
  c('cg03330058', 0.0, 0.0, 10.7256114263043, 0.0),
  c('cg09766383', 10.6575790188034, 0.0, 0.0, 0.0),
  c('cg14837165', 0.0, 0.0, 9.99598408602997, 0.0),
  c('cg23851011', 9.76502215763179, 0.0, 0.0, 0.0),
  c('cg20126106', 0.0, 9.67809005466599, 0.0, 0.0),
  c('hsa-miR-626', 9.18042977230733, 0.0, 0.0, 0.0),
  c('cg20437604', 8.73686511514362, 0.0, 0.0, 0.0),
  c('cg05208878', 0.0, 0.0, 8.72800976748241, 1.43717055291297),
  c('cg10061247', 0.0, 0.0, 8.69020185939158, 0.0),
  c('cg18272264', 0.0, 8.49689752656752, 0.0, 0.0),
  c('cg18017908', 0.0, 0.0, 0.0, 8.38900866669918),
  c('cg02957086', 0.0, 7.92220250954494, 0.0, 0.0),
  c('cg04001333', 6.57712116643126, 0.0, 0.0, 0.0),
  c('cg25000382', 6.34943348999698, 0.0, 0.0, 0.0),
  c('cg08529529', 0.0, 6.32523079156446, 0.0, 0.0),
  c('cg20451680', 0.0, 0.0, 0.0, 6.20260666005312),
  c('cg17711541', 0.0, 6.13907969261119, 0.0, 0.0),
  c('cg27016307', 6.08760518416757, 0.0, 0.0, 0.0),
  c('cg22605063', 0.0, 0.0, 6.06126394641881, 0.0),
  c('cg13531460', 0.0, 6.04866768845529, 0.0, 0.0),
  c('cg02774439', 6.02344898348871, 0.0, 0.0, 0.0),
  c('cg11418559', 0.0, 5.94560689670145, 0.0, 0.0),
  c('cg17063929', 5.82157353880062, 0.0, 0.0, 0.0),
  c('cg12949975', 5.81001149887544, 0.0, 0.0, 0.0),
  c('cg22467534', 0.0, 0.0, 0.0, 5.6858360910492),
  c('hsa-miR-26a-1-3p', 5.61572619347213, 0.0, 0.0, 0.0),
  c('cg22419732', 5.56047706862866, 0.0, 0.0, 0.0),
  c('cg01260219', 5.41711643575096, 0.0, 0.0, 0.0),
  c('cg08504583', 5.17985019232197, 0.0, 0.0, 0.0),
  c('cg06465194', 0.0, 0.0, 0.0, 5.07187190013777),
  c('cg27305662', 4.84282892608778, 0.0, 0.0, 0.0),
  c('cg12365667', 0.0, 0.0, 4.80392176915737, 0.0),
  c('cg00025991', 0.0, 0.0, 4.59201933359941, 0.0),
  c('cg07730301', 0.0, 4.5447211988419, 0.0, 0.0),
  c('hsa-miR-302b-5p', 4.46227006080504, 0.0, 0.0, 0.0),
  c('cg04337944', 0.0, 0.0, 0.0, 4.30167656372427),
  c('cg03490200', 4.18568767702116, 0.0, 0.0, 3.45743868390633),
  c('cg17558126', 0.0, 0.0, 4.09420801714541, 0.0),
  c('cg27158867', 0.0, 0.0, 4.04107672026102, 0.0),
  c('cg13297249', 4.00817509189075, 0.0, 0.0, 0.0),
  c('cg12854483', 0.0, 3.95008047181258, 0.0, 0.0),
  c('cg16008138', 0.0, 0.0, 0.0, 3.83073064063492),
  c('cg25229305', 0.0, 3.81628451863013, 0.0, 0.0),
  c('cg14896003', 3.78391452903543, 0.0, 0.0, 0.0),
  c('cg14070162', 0.0, 3.68992862051634, 0.0, 0.0),
  c('cg24117468', 0.0, 3.66587471454319, 0.0, 0.0),
  c('cg16772514', 0.0, 0.0, 0.0, 3.557619220247),
  c('cg13765785', 0.0, 0.0, 0.0, 3.48824606308588),
  c('hsa-miR-933', 0.0, 3.39460728284747, 0.0, 0.0),
  c('cg00987379', 0.0, 3.36570375881585, 0.0, 0.0),
  c('cg25685838', 0.0, 0.0, 0.0, 3.35796387395198),
  c('cg00407150', 0.0, 0.0, 0.0, 3.35051971723447),
  c('cg04637372', 3.28943797904891, 0.0, 0.0, 0.0),
  c('cg01033938', 3.23679032448033, 0.0, 0.0, 0.0),
  c('hsa-miR-152-3p', 0.0, 0.0, 3.18130889759624, 0.0),
  c('cg13064571', 0.0, 0.0, 0.0, 3.10299834550745),
  c('KHDRBS1TF', 0.0, 0.0, 0.0, 3.04882196510672),
  c('cg22424746', 0.0, 0.0, 0.0, 2.8928942050045),
  c('cg03064067', 2.87132651702591, 0.0, 0.0, 0.0),
  c('cg22253945', 0.0, 2.75518497072303, 0.0, 0.0),
  c('cg23051664', 0.0, 0.0, 0.0, 2.70373814128077),
  c('cg04660410', 0.0, 0.0, 0.0, 2.62813535379197),
  c('cg12603560', 0.0, 2.57376331612129, 0.0, 0.0),
  c('cg14982472', 0.0, 0.0, 0.0, 2.55241896716654),
  c('cg10257049', 0.0, 2.49378560940883, 0.0, 0.0),
  c('cg09076123', 0.0, 2.43325028072658, 0.0, 0.0),
  c('cg09300114', 0.0, 0.0, 0.0, 2.43245715129006),
  c('cg26154999', 0.0, 2.3922075349018, 0.0, 0.0),
  c('cg15154229', 0.0, 0.0, 0.0, 2.26858320455267),
  c('cg01817029', 0.0, 2.26573868497163, 0.0, 0.0),
  c('KDM1ATF', 0.444866508493889, 0.0, 0.0, 2.25118789343509),
  c('ZEB2TF', 0.0, 0.0, 2.21919532871095, 0.0),
  c('cg05226008', 0.0, 0.0, 0.0, 2.19916316278493),
  c('cg10523671', 2.15990034234948, 0.0, 0.0, 0.0),
  c('cg16003238', 0.0, 0.0, 0.0, 2.15924111072103),
  c('MEF2CTF', 0.0, 0.0, 0.0, 2.00763611843047),
  c('cg25072962', 0.0, 0.0, 0.0, 1.9504781361094),
  c('RNGTTTF', 1.94190626232305, 0.0, 0.0, 0.0),
  c('cg10964421', 0.0, 0.0, 0.0, 1.9378318619282),
  c('cg12970081', 1.92159273627954, 0.0, 0.0, 0.0),
  c('cg03019000', 1.9211065847965, 0.0, 0.0, 0.0),
  c('SLA2TF', 0.0, 1.83495982830787, 0.0, 0.0),
  c('XPCTF', 0.0, 1.78990498940381, 0.0, 0.0),
  c('SAP30BP', 0.0, 1.75109674690557, 0.0, 0.0),
  c('SNAI2TF', 0.0, 0.0, 1.73557776013456, 0.0),
  c('STAG1TF', 1.69387689177112, 0.0, 0.0, 0.0),
  c('HEYLTF', 0.0, 1.67631091080329, 0.0, 0.0),
  c('CHD4TF', 0.0, 1.65682610970508, 0.0, 0.0),
  c('cg08465774', 0.0, 1.65401784735319, 0.0, 0.0),
  c('cg10556064', 0.0, 0.0, 0.0, 1.60272835845783),
  c('cg10635061', 0.0, 0.0, 0.0, 1.55053538760639),
  c('cg17279839', 1.54354350725887, 0.0, 0.0, 0.0),
  c('hsa-miR-330-5p', 1.53607144730418, 0.0, 0.0, 0.0),
  c('cg11340260', 0.0, 1.53270536661803, 0.0, 0.0),
  c('TBX5TF', 0.0, 0.0, 1.52408236804918, 0.0),
  c('cg12927772', 1.43907812492329, 0.0, 0.0, 0.0),
  c('cg15777570', 0.0, 0.0, 0.0, 1.43413273168519),
  c('VPS13B', 1.41545633600219, 0.0, 0.0, 0.0995917758805501),
  c('cg09405083', 0.0, 1.4139823671253, 0.0, 0.0),
  c('cg00947019', 0.0, 0.0, 0.0, 1.40591657023924),
  c('cg12907644', 0.0, 0.0, 0.0, 1.4044395893103),
  c('FUSTF', 0.0, 0.0, 0.0, 1.3993177165819),
  c('cg04366367', 0.0, 0.0, 1.39871408580858, 0.0),
  c('cg14532519', 0.0, 0.0, 1.39696696371957, 0.0),
  c('cg01965939', 0.0, 1.37529775761948, 0.0, 0.0),
  c('hsa-miR-33b-3p', 0.0, 1.35795769131141, 0.0, 0.0),
  c('GLIS2TF', 0.0, 0.751122543621175, 1.35694930088188, 0.0),
  c('SPI1TF', 0.0, 1.32050135001699, 0.0, 0.386644365697666),
  c('cg03386869', 0.0, 0.0, 0.0, 1.31609568837869),
  c('BHLHE22TF', 0.0, 0.0, 1.26096005373552, 0.0),
  c('cg01861509', 0.0, 1.25871340803505, 0.0, 0.0),
  c('cg16504798', 1.25682627867354, 0.0, 0.0, 0.0),
  c('hsa-miR-337-5p', 0.0, 1.24795350180996, 0.0, 0.0),
  c('ESRRATF', 1.23147874710873, 0.0, 0.0, 0.465042103816802),
  c('hsa-miR-636', 0.0, 1.22637141712212, 0.0, 0.0),
  c('ZFP1TF', 1.22411308998377, 0.0, 0.0, 0.0),
  c('STAT4TF', 0.0, 1.20785333246884, 0.0, 0.0),
  c('PER2TF', 1.20248822757837, 0.0, 0.0, 0.0),
  c('HLXTF', 0.0, 0.0, 1.17088878300268, 0.0),
  c('BRIP1TF', 1.1622175537322, 0.0, 0.0, 0.0),
  c('RUNX2TF', 0.0, 0.0, 1.16202987968379, 0.0),
  c('TBX21TF', 0.0, 1.11640847689679, 0.0, 0.0),
  c('cg03734783', 0.0, 0.0, 0.0, 1.09684067740271),
  c('CDKN1BTF', 1.04234717375369, 0.0, 0.0, 0.0),
  c('ETV1TF', 0.0, 0.0, 1.04101885221284, 0.0),
  c('TFEBTF', 0.0, 0.0, 0.0, 1.03659518569405),
  c('CIZ1', 0.0, 0.0, 1.02984905377006, 0.0),
  c('cg05010058', 0.0, 1.02370768330375, 0.0, 0.0),
  c('ITGB4', 0.0, 1.00896148188265, 0.0, 0.0),
  c('NFIXTF', 0.0, 0.994919826767217, 0.0, 0.0),
  c('cg00083937', 0.0, 0.0, 0.0, 0.993044816158907),
  c('cg13614181', 0.965958349931712, 0.0, 0.0, 0.0),
  c('cg20725021', 0.0, 0.0, 0.0, 0.94115884110021),
  c('TCF7L1TF', 0.0, 0.754518435717531, 0.0, 0.923533454428546),
  c('FOXP3TF', 0.0, 0.908723226141074, 0.0, 0.0),
  c('NKX6-1TF', 0.900877828174745, 0.0, 0.0, 0.0),
  c('hsa-miR-142-5p', 0.0, 0.879762089747336, 0.0, 0.0),
  c('hsa-miR-548c-5p', 0.0, 0.870578280528505, 0.0, 0.0),
  c('cg27532722', 0.0, 0.0, 0.0, 0.833956869109888),
  c('SMAD3TF', 0.829538559708794, 0.122277772923973, 0.0, 0.0),
  c('hur_6', 0.0, 0.0, 0.816737432293719, 0.0),
  c('hsa-miR-455-3p', 0.0, 0.81502195487019, 0.0, 0.0),
  c('FOXP1TF', 0.0, 0.0, 0.791145295366834, 0.0),
  c('BRF1TF', 0.0, 0.785483494233843, 0.0, 0.0),
  c('hsa-miR-218-5p', 0.0, 0.0, 0.0, 0.782357699029578),
  c('ZEB1TF', 0.0, 0.0, 0.779565558723742, 0.0),
  c('ASXL2TF', 0.0, 0.776349640357374, 0.0, 0.0),
  c('PRDM1TF', 0.0, 0.0, 0.773843180304007, 0.0),
  c('USF1TF', 0.0, 0.763906340927711, 0.0, 0.0),
  c('cg12647587', 0.0, 0.749309249886134, 0.0, 0.0),
  c('cg00622552', 0.0, 0.742656902340062, 0.0, 0.0),
  c('NCOR2TF', 0.0, 0.464973909903333, 0.736831507737552, 0.0),
  c('NUPR1TF', 0.0, 0.73227565334169, 0.0, 0.0),
  c('SP140TF', 0.0, 0.731342225527608, 0.0, 0.0),
  c('HDAC4TF', 0.0, 0.730888120940488, 0.0, 0.0),
  c('KDM4ATF', 0.0, 0.729601757633137, 0.0, 0.0),
  c('CDK6TF', 0.0, 0.722555151304746, 0.0, 0.0),
  c('TCF4TF', 0.0, 0.0, 0.719207714533274, 0.0),
  c('FOXK1TF', 0.0, 0.713811155047529, 0.0, 0.0),
  c('cg10368842', 0.0, 0.0, 0.0, 0.712013636922499),
  c('HIC1TF', 0.0, 0.0, 0.690289116583597, 0.0),
  c('cg04741133', 0.0, 0.687710098414712, 0.0, 0.0),
  c('hsa-miR-877-3p', 0.0, 0.680844707529055, 0.0, 0.0),
  c('NR1H3TF', 0.0, 0.678458732482202, 0.0, 0.0),
  c('cg06537829', 0.0, 0.0, 0.0, 0.66899676609125),
  c('INTS12TF', 0.0, 0.642878782759726, 0.0, 0.0),
  c('cg00658007', 0.641190590239525, 0.0, 0.0, 0.0),
  c('CREMTF', 0.0, 0.640571618778153, 0.0, 0.0),
  c('MSCTF', 0.0, 0.0, 0.638736789966513, 0.0),
  c('cg09243900', 0.627311664335147, 0.0, 0.0, 0.0),
  c('ZSCAN18TF', 0.0, 0.623047031104513, 0.0, 0.0),
  c('cg21096399', 0.611550057062556, 0.0, 0.0, 0.0),
  c('ODF2', 0.0, 0.0, 0.587912085759212, 0.0),
  c('ETV7TF', 0.0, 0.586561480610977, 0.0, 0.0),
  c('cg00891541', 0.585602361330336, 0.0, 0.0, 0.0),
  c('cg26416466', 0.566697189710845, 0.0, 0.0, 0.0),
  c('CCND2TF', 0.0, 0.0, 0.0, 0.552696856687456),
  c('DAND5TF', 0.0, 0.0, 0.0, 0.544863055135611),
  c('cg17518965', 0.542681636653857, 0.0, 0.0, 0.0),
  c('TRIP6TF', 0.539646910712636, 0.0, 0.0, 0.0),
  c('TET3TF', 0.0, 0.536148643841554, 0.0, 0.0),
  c('cg12461141', 0.0, 0.0, 0.0, 0.527071028665829),
  c('DNMT3ATF', 0.0, 0.0, 0.0, 0.507665620098438),
  c('cg17076012', 0.0, 0.0, 0.499695465248605, 0.0),
  c('cg04490714', 0.0, 0.480943892008034, 0.0, 0.0),
  c('ARNT2TF', 0.0, 0.460056890654376, 0.0, 0.0),
  c('cg06911084', 0.43982821323504, 0.0, 0.0, 0.0),
  c('ZNF445TF', 0.0, 0.437054544959848, 0.0, 0.0),
  c('DDIT3TF', 0.0, 0.432884110080819, 0.0, 0.0),
  c('SNORD77|ENSG00000212414.1', 0.424021088185736, 0.0, 0.0, 0.0),
  c('COQ4', 0.0, 0.0, 0.42218478922762, 0.0),
  c('MIR1273A', 0.418775975189632, 0.0, 0.0, 0.0),
  c('cg15973234', 0.0, 0.414944291726249, 0.0, 0.0),
  c('SLC27A4', 0.0, 0.0, 0.41447953866497, 0.0),
  c('PRKCQTF', 0.0, 0.0, 0.412945359340965, 0.0),
  c('URM1', 0.0, 0.0, 0.411555083608572, 0.0),
  c('CERCAM', 0.0, 0.0, 0.411050717271158, 0.0),
  c('cg21184174', 0.393453428393901, 0.0, 0.0, 0.0),
  c('cg19205533', 0.357784789492056, 0.0, 0.0, 0.0),
  c('OSR2', 0.0, 0.0, 0.0, 0.345243939674872),
  c('MIR610', 0.340334683539067, 0.0, 0.0, 0.0),
  c('hsa-miR-22-3p', 0.0, 0.0, 0.336029611022243, 0.0),
  c('hsa-miR-142-3p', 0.0, 0.328903811069404, 0.0, 0.0),
  c('cg00126657', 0.0, 0.0, 0.0, 0.313618470928893),
  c('STAT1TF', 0.0, 0.312706055700439, 0.0, 0.0),
  c('HMGA1P4', 0.0, 0.0, 0.309386356902556, 0.0),
  c('WDR34', 0.0, 0.0, 0.308604648333733, 0.0),
  c('MIR599', 0.0, 0.0, 0.0, 0.308275275342118),
  c('MIR875', 0.0, 0.0, 0.0, 0.307308386518531),
  c('RCOR2TF', 0.0, 0.307281007177914, 0.0, 0.0),
  c('SET', 0.0, 0.0, 0.305465377242087, 0.0),
  c('hsa-miR-379-5p', 0.0, 0.166169999002142, 0.304469589142987, 0.0),
  c('CDK2TF', 0.302840232547439, 0.0, 0.0, 0.0),
  c('UGT2A2', 0.0, 0.30276705999539, 0.0, 0.0),
  c('SPTAN1', 0.0, 0.0, 0.299082536372849, 0.0),
  c('UGT2A1', 0.0, 0.295954252752598, 0.0, 0.0),
  c('XBP1', 0.0, 0.290589167054019, 0.0, 0.0),
  c('CBX1TF', 0.268537221892989, 0.0, 0.0, 0.0),
  c('SMIM6', 0.0, 0.260447033841334, 0.0, 0.0),
  c('SMIM5', 0.0, 0.25679992678123, 0.0, 0.0),
  c('CIITATF', 0.0, 0.0, 0.0, 0.256612174980878),
  c('KLF17TF', 0.0, 0.0, 0.256117533632739, 0.0),
  c('SUZ12TF', 0.250995231362522, 0.0, 0.0, 0.0),
  c('RECQL5', 0.0, 0.245081142337289, 0.0, 0.0),
  c('IRF1TF', 0.0, 0.241613104138695, 0.0, 0.0),
  c('cg04237003', 0.0, 0.0, 0.240400016696337, 0.0),
  c('STK3', 0.0, 0.0, 0.0, 0.235298867588561),
  c('TGIF2TF', 0.207923910188155, 0.0, 0.0, 0.0),
  c('hsa-miR-381-3p', 0.0, 0.207775653804146, 0.0, 0.0),
  c('UGT2B4', 0.0, 0.207452495371487, 0.0, 0.0),
  c('MUC15', 0.199848385517371, 0.0, 0.0, 0.0),
  c('RN7SKP85', 0.0, 0.0, 0.0, 0.189427662811408),
  c('cg02397720', 0.183899228825909, 0.0, 0.0, 0.0),
  c('ZSCAN21TF', 0.0, 0.0, 0.0, 0.183287306032588),
  c('hsa-miR-21-3p', 0.0, 0.0, 0.0, 0.181629722536569),
  c('CD8ATF', 0.0, 0.164903835483929, 0.0, 0.0),
  c('GLE1', 0.0, 0.0, 0.161888377470033, 0.0),
  c('MCM2TF', 0.159093775426182, 0.0, 0.0, 0.0),
  c('TRIM22TF', 0.0, 0.0, 0.0, 0.159039310677714),
  c('CBX5TF', 0.0, 0.0, 0.0, 0.158516084287606),
  c('LCORLTF', 0.147803145629326, 0.0, 0.0, 0.0),
  c('cg05982504', 0.0141616225588279, 0.0, 0.0, 0.138758571907855),
  c('RN7SL560P', 0.0, 0.0, 0.136994942809468, 0.0),
  c('TCF19TF', 0.134597919392258, 0.0, 0.0, 0.0),
  c('NFATC1TF', 0.0, 0.0, 0.0, 0.1332275367767),
  c('KIAA1429', 0.12356115170463, 0.0, 0.0, 0.0),
  c('DEKTF', 0.123431279790718, 0.0, 0.0, 0.0),
  c('SMARCC1TF', 0.0, 0.115336474281265, 0.0, 0.0),
  c('cg16858125', 0.113858178701622, 0.0, 0.0, 0.0),
  c('hsa-miR-452-5p', 0.0, 0.113731851198991, 0.0, 0.0),
  c('RUNX1TF', 0.0, 0.0, 0.108790625603959, 0.0753411342230875),
  c('SPAG1', 0.0, 0.0, 0.0, 0.103915320740848),
  c('hsa-miR-197-3p', 0.0, 0.101788832923724, 0.0, 0.0),
  c('ARNTL2TF', 0.0937538194802619, 0.0, 0.0, 0.0),
  c('cg23539753', 0.0, 0.0, 0.0, 0.0801541081256415),
  c('cg20347268', 0.0, 0.0, 0.0, 0.0786707912147253),
  c('NKX2-3TF', 0.0, 0.0, 0.0672546160056475, 0.0),
  c('cg18390025', 0.0658829546432705, 0.0, 0.0, 0.0),
  c('hsa-miR-199a-5p', 0.0, 0.0, 0.0586923899252452, 0.0),
  c('MIR3151', 0.0, 0.0, 0.0, 0.0484031033634407),
  c('C8orf56', 0.0, 0.0, 0.0, 0.0467406375262494),
  c('POLR2K', 0.0, 0.0, 0.0, 0.0453630876853596),
  c('FBXO43', 0.0, 0.0, 0.0, 0.0436949068576004),
  c('RGS22', 0.0, 0.0, 0.0, 0.0435472483950507),
  c('ATP6V1C1', 0.0, 0.0, 0.0, 0.039588775838652),
  c('MEOX2TF', 0.0, 0.0, 0.0372687382013687, 0.0),
  c('TFAP2CTF', 0.0369572557569777, 0.0, 0.0, 0.0),
  c('TWIST1TF', 0.0, 0.0, 0.0320179063623446, 0.0),
  c('MIR4466', 0.0308754439156182, 0.0, 0.0, 0.0),
  c('RN7SL350P', 0.0, 0.0, 0.0, 0.0304663029569636),
  c('CRY1TF', 0.0295736434403535, 0.0, 0.0, 0.0),
  c('TET1TF', 0.0, 0.0, 0.0, 0.0293839880974186),
  c('HSF2TF', 0.0258279811451888, 0.0, 0.0, 0.0),
  c('cg25162921', 0.0, 0.0, 0.0235734151290711, 0.0),
  c('snoU13|ENSG00000238318.1', 0.0, 0.0151524691011942, 0.0, 0.0),
  c('RUFY3', 0.0, 0.0143958429336343, 0.0, 0.0),
  c('GRSF1', 0.0, 0.0132083639168356, 0.0, 0.0),
  c('cg00107187', 0.0, 0.0090893628058763, 0.0, 0.0),
  c('cg10929387', 0.007528507781128, 0.0, 0.0, 0.0),
  c('ASH1L', 0.0, 0.0040644706436332, 0.0, 0.0),
  c('cg05337441', 0.0, 0.0, 0.0, 0.0023739288639006),
  c('SNORD28|ENSG00000212295.1', 0.0019779805337241, 0.0, 0.0, 0.0),
  c('ELK3TF', 0.0, 0.0, 0.0018024850614233, 0.0),
  c('ZNF512TF', 0.0, 0.0, 0.0, 0.001237057020224),
  c('HOXA5TF', 0.0, 0.0, 0.0011357333995879, 0.0),
  c('NR0B2TF', 0.0, 0.0, 0.0, 0.0003395833727356)
)


variables_differentiated <- c()
variables_immunoreactive <- c()
variables_mesenchymal <- c()
variables_proliferative <- c()


for (variable in variables_contributions) {
  if (variable[2] != 0) {
    variables_differentiated <- c(variables_differentiated, variable[1])
  } else if (variable[3] != 0) {
    variables_immunoreactive <- c(variables_immunoreactive, variable[1])
  } else if (variable[4] != 0) {
    variables_mesenchymal <- c(variables_mesenchymal, variable[1])
  } else if (variable[5] != 0) {
    variables_proliferative <- c(variables_proliferative, variable[1])
  }
}


important_vars_elasticnet <- list(
  differentiated = variables_differentiated,
  immunoreactive = variables_immunoreactive,
  mesenchymal = variables_mesenchymal,
  proliferative = variables_proliferative
)



```

## INTERSECT

```{r}
find_common_vars <- function(list1, list2) {
  common_vars <- lapply(names(list1), function(class) {
    intersect(list1[[class]], list2[[class]])
  })
  names(common_vars) <- names(list1)
  return(common_vars)
}

}

```

#### Plasso vs RF

```{r}
common_vars_PLasso_RF <- find_common_vars(important_vars_PLasso, important_vars_RF)
print(common_vars_PLasso_RF)
```

#### PLSDA VS Priority lasso

```{r}
common_vars_PLasso_PLSDA <- find_common_vars(important_vars_PLasso, important_vars_plsda)

print(common_vars_PLasso_PLSDA)
```

#### PLSADA vs RF

```{r}
common_vars_RF_PLSDA <- find_common_vars(important_vars_RF, important_vars_plsda)
print(common_vars_RF_PLSDA)
```

#### **Elasticnet vs RF**

```{r}
common_vars_elasticnet_RF<- find_common_vars(important_vars_elasticnet, important_vars_RF)

print(common_vars_elasticnet_RF)
```

#### **Elasticnet vs plasso**

```{r}

common_vars_elasticnet_Plasso <- find_common_vars(important_vars_elasticnet, important_vars_PLasso)
print(common_vars_elasticnet_Plasso)
```

#### Elasticnet vs PLSDA

```{r}
common_vars_elasticnet_PLSDA <- find_common_vars(important_vars_elasticnet, important_vars_plsda)
print(common_vars_elasticnet_PLSDA)
```

### INTERSECTION OF THREE MODELS ( EXCEPT BF and PLASSO)

```{r}

find_common_vars_multiple <- function(..., class_names) {
  model_lists <- list(...)
  common_vars <- lapply(class_names, function(class) {
    Reduce(intersect, lapply(model_lists, `[[`, class))
  })
  names(common_vars) <- class_names
  return(common_vars)
}


class_names <- c("differentiated", "immunoreactive", "mesenchymal", "proliferative")

common_vars_all_models <- find_common_vars_multiple(
  important_vars_RF,
  important_vars_plsda,
  important_vars_elasticnet,
  class_names = class_names
)

print(common_vars_all_models)

```

### INTERSECT BINARY

PLSDA, PLASSO

```{r}

# Encontrar coincidencias entre las tres listas
common_vars_binario_pls_lasso <- find_common_vars(important_vars_Plasso_binario, important_vars_plsda _binario)

# Mostrar las variables comunes
print(common_vars_binario_pls_lasso)
```
